#!/bin/bash
set -e

./compile
pip install pyltp
mkdir -p tools
cd tools

wget -c http://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz
wget -c http://downloads.typesafe.com/scala/2.11.2/scala-2.11.2.tgz
tar -xzf WordNet-3.0.tar.gz
tar -xzf scala-2.11.2.tgz
cd ..
mkdir -p target
wget -c http://nlp.stanford.edu/software/stanford-parser-full-2016-10-31.zip
tar -xzf stanford-parser-full-2016-10-31.zip
cd stanford-parser-full-2016-10-31/model
wget -c http://nlp.stanford.edu/software/stanford-chinese-corenlp-2016-10-31-models.jar
jar -xvf stanford-chinese-corenlp-2016-10-31-models.jar
