#!/bin/bash
set -e

./compile
pip install pyltp
mkdir -p tools
cd tools

wget -c http://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz
wget -c http://downloads.typesafe.com/scala/2.11.2/scala-2.11.2.tgz
wget -c http://demo.clab.cs.cmu.edu/cdec/cdec-2014-06-15.tar.gz
tar -xzf cdec-2014-06-15.tar.gz
ln -s cdec-2014-06-15 cdec
tar -xzf WordNet-3.0.tar.gz
tar -xzf scala-2.11.2.tgz

wget -c http://nlp.stanford.edu/software/stanford-parser-full-2016-10-31.zip
tar -xzf stanford-parser-full-2016-10-31.zip
cd stanford-parser-full-2016-10-31
mkdir model
cd model
wget -c http://nlp.stanford.edu/software/stanford-chinese-corenlp-2016-10-31-models.jar
jar -xvf stanford-chinese-corenlp-2016-10-31-models.jar
cp edu/stanford/nlp/models/lexparser/xinhuaFactored.ser.gz ../
